### ISSUE TITLE
Need to exit program twice

### ISSUE THREAD

**Issue by rauland** [codenor/pwgen#4]

**Comment by codenor** [comment]
Temp fix with 18251120062818a0ae733147973af08d5541ea14. Think it has something to do with colorama, removing colorama from logo function seemed to have fixed it on my end, please confirm it is fixed on your end and feel free to close issue if it is fixed.

**Comment by rauland** [comment]
> 

No not fixed, I still have to exit (6) twice

**Comment by codenor** [comment]
Think it had something to do with the logo. Should be fixed with 2baeb4d631a0aba9f7fd5e2adb1376ce241f9e9b, sadly had to remove the logo to fix it. Although what I don't understand is how it was fixed for me temporarily with 18251120062818a0ae733147973af08d5541ea14.

**Comment by codenor** [comment]
I got the bug again, think it is a library bug. I just created my own exit function instead ece1b644f9abd38383e7db22eae05f09c941f1ac.  Should now be fixed, closing the issue because it has to be fixed now.
